//Manuel Ortega Salvador

package pr5;

/**
 *
 * @author Usuario
 */
public enum TipoMensaje {
    MENSAJE_CONEXION,
    MENSAJE_LISTA_USUARIOS,
    MENSAJE_CERRAR_CONEXION,
    MENSAJE_PEDIR_FICHERO,
    MENSAJE_PREPARADO_CLIENTESERVIDOR,
    MENSAJE_CONFIRMACION_CONEXION,
    MENSAJE_CONFIRMACION_LISTA_USUARIOS,
    MENSAJE_EMITIR_FICHERO,
    MENSAJE_PREPARADO_SERVIDORCLIENTE,
    MENSAJE_CONFIRMACION_CERRAR_CONEXION   
}
